UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /


pagina_estatica:
    pattern:    /sitio/{pagina}/
    defaults:   { _controller: OfertaBundle:Sitio:estatica }

#CIUDAD

ciudad_recientes:
    pattern:    /{ciudad}/recientes
    defaults:   { _controller: CiudadBundle:Default:recientes }

ciudad_cambiar:
    pattern:    /ciudad/cambiar-a-{ciudad}
    defaults:   { _controller: CiudadBundle:Default:cambiar }

#TIENDA

tienda_portada:
    pattern:    /{ciudad}/tiendas/{tienda}
    defaults:   { _controller: TiendaBundle:Default:portada }

#OFERTA

oferta:
    pattern:    /{ciudad}/ofertas/{slug}
    defaults:   { _controller: OfertaBundle:Default:oferta }


#Ruta completa de portada (con slug de ciudad)
portada:
    pattern:   /{ciudad}
    defaults:  { _controller: OfertaBundle:Default:portada }


#Ruta Simple de portada
_portada:
    pattern:   /
    defaults:  { _controller: OfertaBundle:Default:portada }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
